# Generated by Django 5.0 on 2024-01-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
    ]
